-- Drop tables for a clean start

DROP TABLE IF EXISTS USER_PREFERENCE;
DROP TABLE IF EXISTS TRAIN_SCHEDULE_STOPPAGES;
DROP TABLE IF EXISTS TRAIN_SCHEDULE;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS USERS;

-- USERS Table
CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE
);

-- TRAIN Table (removed TYPE column)
CREATE TABLE TRAIN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRAIN_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    TOTAL_SEATS INT NOT NULL
);

-- TRAIN_SCHEDULE Table (removed SEAT_CLASS column)
CREATE TABLE TRAIN_SCHEDULE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRAIN_ID BIGINT NOT NULL,
    SOURCE_STATION VARCHAR(100) NOT NULL,
    DESTINATION_STATION VARCHAR(100) NOT NULL,
    DEPARTURE_TIME TIMESTAMP NOT NULL,
    ARRIVAL_TIME TIMESTAMP NOT NULL,
    DURATION_MINUTES INT NOT NULL,
    AVAILABLE_SEATS INT NOT NULL,
    FARE DOUBLE NOT NULL,
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(ID) ON DELETE CASCADE
);

-- TRAIN_SCHEDULE_STOPPAGES Table
CREATE TABLE TRAIN_SCHEDULE_STOPPAGES (
    TRAIN_SCHEDULE_ID BIGINT NOT NULL,
    STOP_ORDER INT NOT NULL,
    STOPPAGES VARCHAR(100),
    FOREIGN KEY (TRAIN_SCHEDULE_ID) REFERENCES TRAIN_SCHEDULE(ID) ON DELETE CASCADE
);

-- USER_PREFERENCE Table (removed type and class related columns)
CREATE TABLE USER_PREFERENCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL UNIQUE,
    SAVED_FILTER_SOURCE VARCHAR(100),
    SAVED_FILTER_DESTINATION VARCHAR(100),
    SAVED_FILTER_MIN_DEPARTURE TIME,
    SAVED_FILTER_MAX_DEPARTURE TIME,
    SAVED_FILTER_MAX_DURATION INT,
    SAVED_FILTER_SORT_BY VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Add to your existing schema.sql
CREATE TABLE IF NOT EXISTS SEAT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRAIN_SCHEDULE_ID BIGINT NOT NULL,
    COACH_NUMBER VARCHAR(10) NOT NULL,
    SEAT_NUMBER VARCHAR(10) NOT NULL,
    COACH_TYPE VARCHAR(20) NOT NULL,
    SEAT_TYPE VARCHAR(10) NOT NULL,
    IS_BOOKED BOOLEAN NOT NULL DEFAULT FALSE,
    FARE DOUBLE NOT NULL,
    FOREIGN KEY (TRAIN_SCHEDULE_ID) REFERENCES TRAIN_SCHEDULE(ID)
);

CREATE TABLE IF NOT EXISTS TRAIN_SCHEDULE_STOPPAGES (
    TRAIN_SCHEDULE_ID BIGINT NOT NULL,
    STOPPAGES VARCHAR(100) NOT NULL,
    STOP_ORDER INT NOT NULL,
    FOREIGN KEY (TRAIN_SCHEDULE_ID) REFERENCES TRAIN_SCHEDULE(ID)
);

CREATE TABLE IF NOT EXISTS USER_PROFILES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    GENDER VARCHAR(10),
    GOVT_ID VARCHAR(12),
    MEAL_PREFERENCE VARCHAR(10),
    NICKNAME VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS BOOKED_SEATS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    SEAT_ID BIGINT NOT NULL,
    TRAIN_SCHEDULE_ID BIGINT NOT NULL,
    BOOKING_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FARE DOUBLE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'CONFIRMED', -- Optional: CONFIRMED, CANCELLED, etc.

    FOREIGN KEY (SEAT_ID) REFERENCES SEAT(ID) ON DELETE CASCADE,
    FOREIGN KEY (TRAIN_SCHEDULE_ID) REFERENCES TRAIN_SCHEDULE(ID) ON DELETE CASCADE
);

-- Ensure this is added to your schema.sql file
-- If the table already exists, this won't create it again
CREATE TABLE IF NOT EXISTS FEEDBACK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    RATING INTEGER NOT NULL,
    COMMENT VARCHAR(500) NOT NULL,
    CATEGORY VARCHAR(50),
    SUBMISSION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
